
version: '3.7'
services:
  
  #############################################################################################
  ###                               DPS service API                                         ###
  #############################################################################################
  service-api:
    image: nginx:latest
    volumes:
      - ./src/service-api/conf/nginx.conf:/etc/nginx/nginx.conf
      # TODO: renable sharing logs
      # - ./nginx-log:/var/log/nginx
    ports:
      - 5050:80
    networks:
      - dps-net

  #############################################################################################
  ###                  DPS service API SPLUNK UNIVERSAL FORWARDER                           ###
  #############################################################################################
  service-api-universalforwarder:
    image: splunk/universalforwarder:7.3.2
    platform: linux/amd64
    volumes:
      - ./.splunk/conf/inputs.conf:/opt/splunkforwarder/etc/system/local/inputs.conf
      - ./.splunk/conf/outputs.conf:/opt/splunkforwarder/etc/system/local/outputs.conf
      # TODO: renable sharing logs
      # - ./nginx-log:/var/log/nginx
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=$SPLUNK_PWD
    ports:
      - "8089"
      - "9997"
    networks:
      - dps-net

  #############################################################################################
  ###                               DPS payment service                                     ###
  #############################################################################################
  payment-service:
    build:
      args:
        - MVN_PROFILES=dps-payment-service,openshift
        - DPS_SERVICE_NAME=dps-payment-service
    environment: 
      - spring_profiles_active=cloud,splunk
      - BAMBORA_PAYMENT_ENDPOINT=https://example.com
      - BAMBORA_MERCHANT_ID=changeme
      - BAMBORA_HASHKEY=SUPERHASHKEY
      - CRC_ENDPOINT_APPROVED=http://approved
      - CRC_ENDPOINT_DECLINED=http://declined
      - CRC_ENDPOINT_ERROR=http://error
      - SPLUNK_URL=https://dps-splunk:8088
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
      - SWAGGER_UI_ENABLED=true
    ports:
      - "8084:8080"
    networks:
      - dps-net
  
  #############################################################################################
  ###        DPS validation service (Driver Fitness Case Management Service)                ###
  #############################################################################################
  dps-validation-service:
    build:
      args:
        - spring_profiles_active=cloud
        - MVN_PROFILES=dps-validation-service,splunk
        - DPS_SERVICE_NAME=dps-validation-service
    environment: 
      - SWAGGER_UI_ENABLED=true
      - DFCMS_BASE_PATH=${DFCMS_BASE_PATH}
      - DFCMS_EIGHT_DIGIT_LICENSE=${DFCMS_EIGHT_DIGIT_LICENSE}
    ports:
      - "8083:8080"
    networks:
      - dps-net

  #############################################################################################
  ###                     DPS Notification Service                                          ###
  #############################################################################################
  dps-notification-service:
    build:
      args:
        - MVN_PROFILES=dps-notification-service
        - DPS_SERVICE_NAME=dps-notification-service
    environment: 
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5054:8080"
    networks:
      - dps-net

  #############################################################################################
  ###                     VIPS Notification Worker                                          ###
  #############################################################################################
  vips-notification-worker:
    build:
      args:
        - MVN_PROFILES=vips-notification-worker
        - DPS_SERVICE_NAME=vips-notification-worker
    ports:
      - "5056:8080"
    environment: 
      - RABBITMQ_HOST=rabbitmq
      - FIGCR_BASE_PATH=${FIGCR_BASE_PATH}
      - VIPS_BASE_PATH=${VIPS_BASE_PATH}
      - VIPS_USERNAME=${VIPS_USERNAME}
      - VIPS_PASSWORD=${VIPS_PASSWORD}
    networks:
      - dps-net

  #############################################################################################
  ###                             SFTP SERVER                                               ###
  #############################################################################################
  dps-sftp:
    image: atmoz/sftp
    platform: linux/amd64
    ports:
      - "22:22"
    command: admin:admin:::upload
    networks:
      - dps-net

  #############################################################################################
  ###                             RABBIT MQ SERVER                                          ###
  #############################################################################################
  dps-rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    platform: linux/amd64
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - data-rabbit:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always
    networks:
      - dps-net

  #############################################################################################
  ###                                 SPLUNK DEV BOX                                        ###
  #############################################################################################
  dps-splunk:
    image: splunk/splunk:8.2.5
    platform: linux/amd64
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PWD}
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8088:8088"
      - "8089:8089"
      - "9997:9997"
    networks:
      - dps-net


  #############################################################################################
  ###                                 REDIS SERVER                                          ###
  #############################################################################################
  dps-redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass admin
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always
    networks:
      - dps-net

  #############################################################################################
  ###                                 REDIS COMMANDER                                       ###
  #############################################################################################
  dps-redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    platform: linux/amd64
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=dps-redis
      - REDIS_PASSWORD=admin
    ports:
      - "8081:8081"
    networks:
      - dps-net


volumes:
  data-rabbit:
  data-redis:

networks: 
  dps-net:
    driver: "bridge"
