kind: Template
apiVersion: v1
metadata:
  name: dps-payment-service-deployment-config
  creationTimestamp: null
parameters:
  - name: APP_NAME
    displayName: Name
    description: A prefix appended to all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: true
  - name: SOURCE_CONTEXT_DIR
    required: true
  - name: GIT_REPO
    required: true
  - name: REPO_REF
    required: true
  - name: PROJECT_PREFIX
    required: true
  - name: APP_NAME
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      creationTimestamp:
      labels: ${APP_NAME}:latest
        io.kompose.service: 
      name: ${APP_NAME}
    spec:
      ports:
      - name: "8081"
        port: 8081
        targetPort: 8081
      selector:
        io.kompose.service: ${APP_NAME}
    status:
      loadBalancer: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      creationTimestamp:
      labels:
        io.kompose.service: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      tags:
      - annotations: null
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
        generation: null
        importPolicy: {}
        name: latest
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=${GIT_REPO}
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      replicas: 2
      selector:
        io.kompose.service: ${APP_NAME}
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp:
          labels:
            io.kompose.service: ${APP_NAME}
        spec:
          containers:
          - image: ''
            name: ${APP_NAME}
            ports:
            - containerPort: 8081
            resources: {}
          restartPolicy: Always
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - ${APP_NAME}
          from:
            kind: ImageStreamTag
            name: ${APP_NAME}:latest
        type: ImageChange
    status: {}
