apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  creationTimestamp: 
  labels:
    app: figaro-validation-service
    template: master-build-pipeline
  name: figaro-validation-service
  namespace: pjztlm-tools
  resourceVersion: '1652783471'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/pjztlm-tools/buildconfigs/figaro-validation-service
  uid: 649a5249-5d75-11ea-8a92-0050568379a2
spec:
  completionDeadlineSeconds: 1800
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'figaro-validation-service:latest'
  postCommit: {}
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 1Gi
  runPolicy: Serial
  source:
    contextDir: src/figaro-validation-service
    git:
      ref: master
      uri: 'https://github.com/bcgov/jag-dps'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: MAVEN_MIRROR_URL
          value: 'http://nexus:8081/repository/dps-group/'
      from:
        kind: ImageStreamTag
        name: 'java:8'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 1
