apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: dps-cronjob
  spec:
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
            labels:
              name: dps-job
              parent: dps-cronjob
          spec:
            containers:
            - args:
              - -c
              - 'curl -XPOST ''http://dps-email-worker/dpsemailworker/job/error''
                --header ''Content-Type: application/json'''
              command:
              - /bin/sh
              image: centos:centos7
              imagePullPolicy: Always
              name: dps-job-pod
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: '*/30 * * * *'
    startingDeadlineSeconds: 200
    successfulJobsHistoryLimit: 3
    suspend: true
  status:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: vips-cronjob
  spec:
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
            labels:
              name: vips-job
              parent: vips-cronjob
          spec:
            containers:
            - args:
              - -c
              - 'curl -XPOST ''http://vips-email-worker/dpsemailworker/job/error''
                --header ''Content-Type: application/json'''
              command:
              - /bin/sh
              image: centos:centos7
              imagePullPolicy: IfNotPresent
              name: vips-job-pod
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: 10,40 * * * *
    startingDeadlineSeconds: 200
    successfulJobsHistoryLimit: 3
    suspend: true
  status:
kind: List
metadata: {}
