name: Build & Push DPS-Email-Poller to Artifactory
permissions:
  contents: write
on:
  push:
    branches: 'r'
    paths:
        - "src/dps-email-poller/**"
        - ".github/workflows/dev-dps-email-poller.yml"
  workflow_dispatch:

env:
  IMAGE_NAME: dps-email-poller
  WORKING_DIRECTORY: .
  IMAGE_TAG: dev
  BRANCH_NAME: develop
  NEXUS_URL: ${{secrets.NEXUS_URL}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Get SHORT_SHA to tag images
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
       
      - name: Docker Build DPS Email Poller Image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker buildx build \
          --load \
          --build-arg DPS_SERVICE_NAME=${{ env.IMAGE_NAME }} \
          --build-arg MVN_PROFILES=${{ env.IMAGE_NAME }},openshift \
          -t artifacts.developer.gov.bc.ca/d043-dps/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          .
  
      - name: Docker Push to Artifactory
        id: publish
        run: |
          docker push artifacts.developer.gov.bc.ca/d043-dps/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
        #   Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: artifacts.developer.gov.bc.ca/d043-dps/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL
      
      - name: Set GitOps SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Update Helm Values and Commit
        id: helm
        run: |
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "DPS GitHub Actions"
          git clone -b ${{ env.BRANCH_NAME }} --single-branch git@github.com:bcgov-c/tenant-gitops-043918.git
          
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test
          cd tenant-gitops-043918/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/deptag: .*/deptag: ${{ env.IMAGE_TAG }} # Image Updated on $DATETIME/" ../deploy/dev_values.yaml
          sed -i "s/depversion: .*/depversion: ${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/dev_values.yaml
          
          sed -i "s/deptag: .*/deptag: ${{ env.IMAGE_TAG }} # Image Updated on $DATETIME/" dps-email-poller/values.yaml
          sed -i "s/depversion: .*/depversion: ${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" dps-email-poller/values.yaml
          
          git add .
          
          git add ../deploy/dev_values.yaml
          
          # Repackage Helm Chart      

          cd gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Dev DPS image tag"
          git push origin ${{ env.BRANCH_NAME }} # Update the branch name as needed