name: Tag & Push DPS to Prod
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        description: App to be deployed
        type: choice
        options:
          - dps-email-poller
          - dps-email-worker
          - dps-notification-service
          - dps-payment-service
          - dps-validation-service
          - vips-notification-worker
env:
  IMAGE_NAME: ${{ github.event.inputs.app_name }}
  WORKING_DIRECTORY: .
  IMAGE_TAG: prod
  BRANCH_NAME: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Tag prefix for Image
        run: |
          if [[ ${{ github.event.inputs.app_name }} == 'dps-email-poller' ]]; then
              echo "TAG_PREFIX=dep" >> "$GITHUB_ENV"
              echo "REPO=d043-dps" >> "$GITHUB_ENV"
          fi
          if [[ ${{ github.event.inputs.app_name }} == 'dps-email-worker' ]]; then
              echo "TAG_PREFIX=dew" >> "$GITHUB_ENV"
              echo "REPO=d043-dps" >> "$GITHUB_ENV"
          fi
          if [[ ${{ github.event.inputs.app_name }} == 'dps-notification-service' ]]; then
              echo "TAG_PREFIX=dns" >> "$GITHUB_ENV"
              echo "REPO=d043-dps" >> "$GITHUB_ENV"
          fi
          if [[ ${{ github.event.inputs.app_name }} == 'dps-payment-service' ]]; then
              echo "TAG_PREFIX=dps" >> "$GITHUB_ENV"
              echo "REPO=d043-dps" >> "$GITHUB_ENV"
          fi
          if [[ ${{ github.event.inputs.app_name }} == 'dps-validation-service' ]]; then
              echo "TAG_PREFIX=dvs" >> "$GITHUB_ENV"
              echo "REPO=d043-dps" >> "$GITHUB_ENV"
          fi
          if [[ ${{ github.event.inputs.app_name }} == 'vips-notification-worker' ]]; then
              echo "TAG_PREFIX=vnw" >> "$GITHUB_ENV"
              echo "REPO=d043-vips" >> "$GITHUB_ENV"
          fi

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Get SHORT_SHA to tag images
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"
      
      - name: Docker Backup
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker pull artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:prod
          docker tag artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:prod artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:prod-backup
          docker push artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:prod-backup
  

      - name: Docker Pull and Tag DPS Image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker pull artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:test
          docker tag artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:test artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Docker Push to Artifactory
        id: publish
        run: |
          docker push artifacts.developer.gov.bc.ca/${{ env.REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Set GitOps SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Update Helm Values and Commit
        id: helm
        run: |
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "DPS GitHub Actions"
          git clone -b ${{ env.BRANCH_NAME }} --single-branch git@github.com:bcgov-c/tenant-gitops-043918.git
          
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test
          cd tenant-gitops-043918/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/${{ env.TAG_PREFIX }}tag: .*/${{ env.TAG_PREFIX }}tag: ${{ env.IMAGE_TAG }} # Image Updated on $DATETIME/" ../deploy/prod_values.yaml
          sed -i "s/${{ env.TAG_PREFIX }}version: .*/${{ env.TAG_PREFIX }}version: ${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/prod_values.yaml
          
          git add .
          
          git add ../deploy/prod_values.yaml
          
          # Repackage Helm Chart      

          cd gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update PROD DPS image tag"
          git push origin ${{ env.BRANCH_NAME }} # Update the branch name as needed
