# Scan the latest build that is on Openshift
name: Trivy Scan
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        description: App to be deployed
        type: choice
        options:
          - dps-email-poller
          - dps-email-worker
          - dps-notification-service
          - dps-payment-service
          - dps-validation-service
          - vips-notification-worker
env:
  IMAGE_NAME: ${{ github.event.inputs.app_name }}
  WORKING_DIRECTORY: .

jobs:
  trivy:
    name: Scan Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at the chosen tag
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Build ${{ env.IMAGE_NAME }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker buildx build \
          --load \
          --build-arg DPS_SERVICE_NAME=${{ env.IMAGE_NAME }} \
          --build-arg MVN_PROFILES=${{ env.IMAGE_NAME }},openshift \
          -t ${{ env.IMAGE_NAME }}:latest \
          .
      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: sarif
          output: trivy-results.sarif
          exit-code: 0
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif